os:
  - linux
language: php
dist: trusty
php:
  - '7.4'
services:
  - docker
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS laravel;'
  - cd app
before_script:
  - composer self-update --stable
jobs:
  include:
    - stage: "Tests"                
      name: "Unit Test PHP"  
      script: 
      - cp .env.example .env
      - composer install
      - php artisan key:generate
      - php artisan migrate
      - php artisan test